loading data
calculating mask sum
creating plottable data
plotting....
('Saving', './temp/002test')
Traceback (most recent call last):
  File "3d_animation_parallel_jobs.py", line 104, in <module>
    create_frame(frame, verts, faces, non_zero_positions, rgba_colors, file_name, folder)
  File "3d_animation_parallel_jobs.py", line 99, in create_frame
    plt.savefig(folder + str(frame).zfill(3) + file_name, bbox_inches = "tight")
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 710, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 526, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 624, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/Users/mcrichter/anaconda3/envs/theano_py27/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 609, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
IOError: [Errno 2] No such file or directory: './temp/002test.png'
